### ISSUE TITLE
API v10 tracking issue

### ISSUE THREAD

**Issue by Th3-M4jor** [Kraigie/nostrum#397]
With the recent deprecation of v8 and v9 becoming deprecated in April, we should probably jump directly to v10. The downside there is that this would be a breaking change due to the requirement to specify the message content intent.
Meaning we'd be releasing `0.6.0` not long after `0.5.0`.

- [ ] Thread support
- [ ] Deprecation of `embed` field in messages
- [ ] Existing attachments needing to be specified when editing a message to add new ones
- [ ] Message Content Intent

**Comment by jchristgit** [comment]
Thanks for opening this! The task list is super useful.

>  Existing attachments needing to be specified when editing a message to add new ones

This is probably not something we can (sanely) / should do in nostrum, right?

**Comment by Th3-M4jor** [comment]
Probably just needs to be something we leave to the user to handle, you're right about feasibility. A note in the docs would be enough.

**Comment by TwistingTwists** [comment]
Does this library support v10 yet?

**Comment by skwerlman** [comment]
> Does this library support v10 yet?

Yes, as of 0.6 v10 is used
